CREATE TABLE IF NOT EXISTS users (
    user_uuid    VARCHAR(36) PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    role         VARCHAR(255),
    team         VARCHAR(255),
    organization VARCHAR(255),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS machines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid  VARCHAR(36) NOT NULL,
    machine_id VARCHAR(255) NOT NULL,
    last_seen  TIMESTAMP NOT NULL,
    CONSTRAINT fk_machines_user FOREIGN KEY (user_uuid) REFERENCES users(user_uuid) ON DELETE CASCADE,
    CONSTRAINT uq_user_machine UNIQUE (user_uuid, machine_id)
);

CREATE INDEX IF NOT EXISTS idx_machines_last_seen ON machines(last_seen);

CREATE TABLE IF NOT EXISTS messages (
    id         VARCHAR(12) PRIMARY KEY,
    from_uuid  VARCHAR(36) NOT NULL,
    to_uuid    VARCHAR(36) NOT NULL,
    from_name  VARCHAR(255),
    to_name    VARCHAR(255),
    from_actor VARCHAR(16) NOT NULL DEFAULT 'human',
    msg_type   VARCHAR(32) NOT NULL DEFAULT 'message',
    intent     VARCHAR(32) NOT NULL DEFAULT 'message',
    thread_id  VARCHAR(32),
    subject    VARCHAR(512),
    body       CLOB NOT NULL,
    sent_at    TIMESTAMP NOT NULL,
    read_at    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_messages_to_uuid ON messages(to_uuid);
CREATE INDEX IF NOT EXISTS idx_messages_from_uuid ON messages(from_uuid);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id);

CREATE TABLE IF NOT EXISTS kb_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    entry_key  VARCHAR(512) NOT NULL,
    content    CLOB NOT NULL,
    tags       VARCHAR(1024),
    author     VARCHAR(255),
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kb_updated ON kb_entries(updated_at);
