CREATE TABLE IF NOT EXISTS users (
    user_uuid    VARCHAR(36) PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    role         VARCHAR(255),
    team         VARCHAR(255),
    organization VARCHAR(255),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS machines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid  VARCHAR(36) NOT NULL,
    machine_id VARCHAR(255) NOT NULL,
    last_seen  TIMESTAMP NOT NULL,
    CONSTRAINT fk_machines_user FOREIGN KEY (user_uuid) REFERENCES users(user_uuid) ON DELETE CASCADE,
    CONSTRAINT uq_user_machine UNIQUE (user_uuid, machine_id)
);

CREATE INDEX IF NOT EXISTS idx_machines_last_seen ON machines(last_seen);

CREATE TABLE IF NOT EXISTS messages (
    id         VARCHAR(12) PRIMARY KEY,
    from_uuid  VARCHAR(36) NOT NULL,
    to_uuid    VARCHAR(36) NOT NULL,
    from_name  VARCHAR(255),
    to_name    VARCHAR(255),
    from_actor VARCHAR(16) NOT NULL DEFAULT 'human',
    msg_type   VARCHAR(32) NOT NULL DEFAULT 'message',
    intent     VARCHAR(32) NOT NULL DEFAULT 'message',
    thread_id  VARCHAR(32),
    subject    VARCHAR(512),
    body       CLOB NOT NULL,
    sent_at    TIMESTAMP NOT NULL,
    read_at    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_messages_to_uuid ON messages(to_uuid);
CREATE INDEX IF NOT EXISTS idx_messages_from_uuid ON messages(from_uuid);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id);

CREATE TABLE IF NOT EXISTS kb_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    entry_key  VARCHAR(512) NOT NULL,
    content    CLOB NOT NULL,
    tags       VARCHAR(1024),
    author     VARCHAR(255),
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kb_updated ON kb_entries(updated_at);

CREATE TABLE IF NOT EXISTS project_sessions (
    user_uuid  VARCHAR(36) NOT NULL,
    repo_id    VARCHAR(512) NOT NULL,
    machine_id VARCHAR(255) NOT NULL,
    last_seen  TIMESTAMP NOT NULL,
    CONSTRAINT pk_project_sessions PRIMARY KEY (user_uuid, repo_id, machine_id),
    CONSTRAINT fk_project_sessions_user FOREIGN KEY (user_uuid) REFERENCES users(user_uuid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_project_sessions_repo ON project_sessions(repo_id, last_seen);

CREATE TABLE IF NOT EXISTS api_systems (
    system_key  VARCHAR(255) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description CLOB,
    updated_at  TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS api_modules (
    system_key  VARCHAR(255) NOT NULL,
    module_key  VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description CLOB,
    updated_at  TIMESTAMP NOT NULL,
    CONSTRAINT pk_api_modules PRIMARY KEY (system_key, module_key),
    CONSTRAINT fk_api_modules_system FOREIGN KEY (system_key)
        REFERENCES api_systems(system_key) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_operations (
    api_id       VARCHAR(512) PRIMARY KEY,
    system_key   VARCHAR(255) NOT NULL,
    module_key   VARCHAR(255) NOT NULL,
    operation_name VARCHAR(255) NOT NULL,
    api_kind     VARCHAR(64) NOT NULL,
    capability   CLOB NOT NULL,
    signature    CLOB NOT NULL,
    auth_rule    CLOB,
    idempotency  CLOB,
    source_repo  VARCHAR(1024),
    source_path  VARCHAR(1024),
    source_owner VARCHAR(255),
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_api_operations_module FOREIGN KEY (system_key, module_key)
        REFERENCES api_modules(system_key, module_key)
);

CREATE TABLE IF NOT EXISTS api_versions (
    api_id          VARCHAR(512) NOT NULL,
    version         VARCHAR(128) NOT NULL,
    lifecycle_status VARCHAR(32) NOT NULL
        CHECK (lifecycle_status IN ('DEVELOPING','RELEASED','SUPERSEDED','DEPRECATED','RETIRED')),
    capability      CLOB NOT NULL,
    signature       CLOB NOT NULL,
    auth_rule       CLOB,
    idempotency     CLOB,
    source_repo     VARCHAR(1024),
    source_path     VARCHAR(1024),
    source_owner    VARCHAR(255),
    origin_type     VARCHAR(32) NOT NULL DEFAULT 'NATIVE',
    discovery_confidence VARCHAR(16),
    scan_id         VARCHAR(255),
    approval_ref    VARCHAR(1024),
    source_commit   VARCHAR(255),
    content_hash    VARCHAR(64) NOT NULL,
    embedding_model VARCHAR(255),
    embedding_dims  INTEGER,
    embedding       CLOB,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    released_at     TIMESTAMP,
    CONSTRAINT pk_api_versions PRIMARY KEY (api_id, version),
    CONSTRAINT fk_api_versions_operation FOREIGN KEY (api_id)
        REFERENCES api_operations(api_id) ON DELETE CASCADE
);

ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS capability CLOB;
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS signature CLOB;
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS auth_rule CLOB;
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS idempotency CLOB;
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS source_repo VARCHAR(1024);
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS source_path VARCHAR(1024);
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS source_owner VARCHAR(255);
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS origin_type VARCHAR(32) DEFAULT 'NATIVE';
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS discovery_confidence VARCHAR(16);
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS scan_id VARCHAR(255);
ALTER TABLE api_versions ADD COLUMN IF NOT EXISTS approval_ref VARCHAR(1024);

CREATE TABLE IF NOT EXISTS api_parameters (
    api_id       VARCHAR(512) NOT NULL,
    version      VARCHAR(128) NOT NULL,
    direction    VARCHAR(16) NOT NULL,
    ordinal      INTEGER NOT NULL,
    param_name   VARCHAR(255) NOT NULL,
    param_type   VARCHAR(512),
    description  CLOB,
    is_required  BOOLEAN NOT NULL,
    CONSTRAINT pk_api_parameters PRIMARY KEY (api_id, version, direction, ordinal),
    CONSTRAINT fk_api_parameters_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_usage_guidance (
    api_id       VARCHAR(512) NOT NULL,
    version      VARCHAR(128) NOT NULL,
    guidance_type VARCHAR(32) NOT NULL,
    ordinal      INTEGER NOT NULL,
    guidance_text CLOB NOT NULL,
    CONSTRAINT pk_api_usage PRIMARY KEY (api_id, version, guidance_type, ordinal),
    CONSTRAINT fk_api_usage_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_errors (
    api_id      VARCHAR(512) NOT NULL,
    version     VARCHAR(128) NOT NULL,
    error_code  VARCHAR(255) NOT NULL,
    description CLOB,
    CONSTRAINT pk_api_errors PRIMARY KEY (api_id, version, error_code),
    CONSTRAINT fk_api_errors_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_side_effects (
    api_id      VARCHAR(512) NOT NULL,
    version     VARCHAR(128) NOT NULL,
    ordinal     INTEGER NOT NULL,
    effect_text CLOB NOT NULL,
    CONSTRAINT pk_api_side_effects PRIMARY KEY (api_id, version, ordinal),
    CONSTRAINT fk_api_side_effects_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_discovery_evidence (
    api_id       VARCHAR(512) NOT NULL,
    version      VARCHAR(128) NOT NULL,
    ordinal      INTEGER NOT NULL,
    evidence_kind VARCHAR(64) NOT NULL,
    source_path  VARCHAR(1024) NOT NULL,
    source_line  INTEGER,
    source_symbol VARCHAR(512),
    detail       CLOB,
    CONSTRAINT pk_api_discovery_evidence PRIMARY KEY (api_id, version, ordinal),
    CONSTRAINT fk_api_discovery_evidence_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_relations (
    api_id             VARCHAR(512) NOT NULL,
    version            VARCHAR(128) NOT NULL,
    relation_type      VARCHAR(64) NOT NULL,
    target_api_id      VARCHAR(512) NOT NULL,
    target_version     VARCHAR(128),
    CONSTRAINT pk_api_relations PRIMARY KEY
        (api_id, version, relation_type, target_api_id),
    CONSTRAINT fk_api_relations_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_lifecycle_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_id         VARCHAR(512) NOT NULL,
    version        VARCHAR(128) NOT NULL,
    from_status    VARCHAR(32),
    to_status      VARCHAR(32) NOT NULL,
    actor          VARCHAR(255),
    note           CLOB,
    related_version VARCHAR(128),
    occurred_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_api_events_version FOREIGN KEY (api_id, version)
        REFERENCES api_versions(api_id, version) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_api_operations_scope
    ON api_operations(system_key, module_key, operation_name);
CREATE INDEX IF NOT EXISTS idx_api_versions_status
    ON api_versions(lifecycle_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_api_relations_target
    ON api_relations(target_api_id);
